#!/bin/sh

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 addr experiment"
    exit 1
fi

mkdir -p "$(dirname /dev/shm/memtier/"$2"_GET.csv)"

./memtier_benchmark/memtier_benchmark -s "$1" -p 11211 -P memcache_text --print-percentiles 50,99,99.5,99.9 \
                                      --test-time=300 --json-out-file="$2.json" --hdr-file-prefix="$2" -o "$2.out" \
                                      --get-samples="/dev/shm/memtier/$2_GET.csv"

./csv_to_npy "/dev/shm/memtier/$2_GET.csv" "$2_GET.npz"
rm -vf "/dev/shm/memtier/$2_GET.csv"
