#!/bin/sh

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 experiment [args]"
    exit 1
fi

experiment="$1"
shift

mkdir -p "$(dirname /dev/shm/memtier/"$experiment"_GET.csv)"

./memtier_benchmark/memtier_benchmark $* -P memcache_text --print-percentiles 50,99,99.5,99.9 \
                                      --test-time=300 --json-out-file="$experiment.json" --hdr-file-prefix="$experiment" \
				      -o "$experiment.out" \
                                      --get-samples="/dev/shm/memtier/$experiment.csv"

./csv_to_npy "/dev/shm/memtier/$experiment.csv" "$experiment.npz"
rm -vf "/dev/shm/memtier/$experiment.csv"
