#!/bin/sh

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 experiment [args]"
    exit 1
fi

experiment="$1"
shift

get_samples_tmp="/dev/shm/memtier/${experiment}_GET.csv"

mkdir -p "$(dirname "$get_samples_tmp")"

./memtier_benchmark/memtier_benchmark "$@" -P memcache_text --print-percentiles 50,99,99.5,99.9 \
                                      -n 40000 --json-out-file="${experiment}.json" --hdr-file-prefix="$experiment" \
				      -o "${experiment}.out" \
                                      --get-samples="$get_samples_tmp"

./csv_to_npy "$get_samples_tmp" "${experiment}_GET.npz"
rm -vf "$get_samples_tmp"
