#!/bin/sh

set -e

src="."
dest="~/pac-sw" # watch out for var. expansion

sync_only=false

while getopts ":h:d:s:S" opt; do
    case $opt in
        h)
            host=$OPTARG
            ;;
        d)
            dest=$OPTARG
            ;;
        s)
            src=$OPTARG
            ;;
        S)
            sync_only=true
            ;;
        \?)
            echo "Invalid option: $OPTARG" 1>&2
            exit 1
            ;;
        :)
            echo "Invalid option: $OPTARG requires an argument" 1>&2
            exit 1
            ;;
    esac
done

shift $(( OPTIND - 1 ))

tmpfile=$(mktemp)
git ls-files --recurse-submodules > "$tmpfile"

rsync -azP --files-from="$tmpfile" "$src"/ "$host":"$dest"

rm "$tmpfile"

sleep 0.2

if ! $sync_only; then
    # Hack for Emacs to properly resolve compilation errors
    echo "Entering directory \`$src'"
    ssh "$host" "cd $dest && make $*"
fi
