#!/usr/bin/env bash

set -e

PAC_SW=$(readlink -e ../..)

suite=cortexsuite

sudo taskset -cp 2 $$
sudo renice -n -20 $$

# User debugfs access until reboot
sudo chmod a+rx /sys/kernel/debug

### Enable kpacd
echo   | sudo sh -c 'tee /sys/kernel/debug/kpacd/*/cpumask'
echo 2 | sudo sh -c 'tee /sys/kernel/debug/kpacd/3/cpumask'

# baseline
env CFLAGS="-O2"					\
    ../bench.py --suite "$suite"

# native
env CFLAGS="-O2 -mbranch-protection=pac-ret"		\
    ../bench.py --suite "$suite"

# svc virtualization
env CFLAGS="-O2 -mbranch-protection=pac-ret"		\
    LD_PRELOAD="$PAC_SW/libkpac/libkpac.so"		\
    LIBKPAC_SVC=1					\
    ../bench.py --suite "$suite"

# syscall
for scope in strong all; do
    env CFLAGS="-O2"					\
        ../bench.py --suite "$suite" --variant syscall --scope "$scope"
done

# kpacd
for scope in strong all; do
    env CFLAGS="-O2"					\
        ../bench.py --suite "$suite" --variant kpacd --scope "$scope"
done

# paravirtualization
env CFLAGS="-O2 -mbranch-protection=pac-ret"		\
    LD_PRELOAD="$PAC_SW/libkpac/libkpac.so"		\
    LIBKPAC_SVC=0					\
    ../bench.py --suite "$suite"
