#!/usr/bin/env bash

set -e

suite=cortexsuite

taskset -cp 2 $$
renice -n -20 $$

### Disable kpacd
echo | tee /sys/kernel/debug/kpacd/*/cpumask

# baseline
env CFLAGS="-O2"					\
    ../bench.py --suite "$suite"

# svc virtualization
env CFLAGS="-O2 -mbranch-protection=pac-ret"		\
    LD_PRELOAD="$HOME/pac-sw/libkpac/libkpac-kpacd.so"	\
    LIBKPAC_MODE=svc-only				\
    ../bench.py --suite "$suite"

# pac-pl
for scope in char strong all; do
    env CFLAGS="-O2"					\
        LD_PRELOAD="$HOME/pac-sw/pac-pl/pac-pl.so"	\
        ../bench.py --suite "$suite" --variant pac-pl --scope "$scope"
done

# syscall
for scope in char strong all; do
    env CFLAGS="-O2"					\
        ../bench.py --suite "$suite" --variant syscall --scope "$scope"
done

### Enable kpacd
echo 2 > /sys/kernel/debug/kpacd/3/cpumask

# kpacd
for scope in char strong all; do
    env CFLAGS="-O2"					\
        ../bench.py --suite "$suite" --variant kpacd --scope "$scope"
done

# paravirtualization with kpacd
env CFLAGS="-O2 -mbranch-protection=pac-ret"		\
    LD_PRELOAD="$HOME/pac-sw/libkpac/libkpac-kpacd.so"	\
    LIBKPAC_MODE=kpac-svc				\
    ../bench.py --suite "$suite"

# paravirtualization with pac-pl
# Note: needs kernel with pac-pl backend
# env CFLAGS="-mbranch-protection=pac-ret"		\
#     LD_PRELOAD="$PAC_SW/libkpac/libkpac-pac-pl.so"	\
#     LIBKPAC_MODE=kpac-svc				\
#     ../bench.py --suite "$suite"
