#!/usr/bin/env bash

set -e

suite=tacle-bench-full

taskset -cp 2 $$
renice -n -20 $$

### Disable kpacd
echo | tee /sys/kernel/debug/kpacd/*/cpumask

# baseline
../bench.py --suite "$suite"

# svc virtualization
env CFLAGS="-mbranch-protection=pac-ret"		\
    LD_PRELOAD="$HOME/pac-sw/libkpac/libkpac.so"	\
    LIBKPAC_SVC=1					\
    ../bench.py --suite "$suite"

# pac-pl
for scope in char strong all; do
    env LD_PRELOAD="$HOME/pac-sw/pac-pl/pac-pl.so"	\
        ../bench.py --suite "$suite" --variant pac-pl --scope "$scope"
done

# syscall (char, strong, all)
for scope in char strong all; do
    ../bench.py --suite "$suite" --variant syscall --scope "$scope"
done

### Enable kpacd
echo 2 > /sys/kernel/debug/kpacd/3/cpumask

# kpacd
for scope in char strong all; do
    ../bench.py --suite "$suite" --variant kpacd --scope all
done

# paravirtualization
env CFLAGS="-mbranch-protection=pac-ret"		\
    LD_PRELOAD="$HOME/pac-sw/libkpac/libkpac.so"	\
    LIBKPAC_SVC=0					\
    ../bench.py --suite "$suite"
