#!/usr/bin/python3

import sys
import matplotlib.pyplot as plt
import numpy as np

def reject_outliers(data, m=2):
    return data[abs(data - np.mean(data)) < m * np.std(data)]

def plot(ax, b, name, range=None):
    #b = reject_outliers(b, 2)
    ax.hist(b, bins=512, range=range)
    ax.axvline(b.mean(), color='k', linestyle='dashed', linewidth=1)
    ax.set_yscale('log')
    ax.set_title(name + f": {b.mean()}")

fig, ax = plt.subplots(len(sys.argv)-1, 1, sharex=True)

a = {}

for i, v in enumerate(sys.argv[1:]):
    a[v] = np.load(v)['arr_0']

ranges = [(np.amin(i), np.amax(i)) for i in a.values()]
full_range = (min([i[0] for i in ranges]),
              max([i[1] for i in ranges]))

for i, v in enumerate(a):
    this_ax = ax if len(sys.argv) == 2 else ax[i]

    plot(this_ax, a[v], v, full_range)

plt.show()
